### ISSUE TITLE
Separate kingpin into 2 dataframes - on that maxes out at 100 rows, and a full archive

### ISSUE THREAD

**Issue by AYu1804** [herts-phei/kingpin#22]
This is to ensure that each kingpin function is fast when updating the kingpin dataset. As time goes on and the kingpin dataset increases in rows the function will work slower. Separating the archive kingpin and the "recent" one that is scheduled to merge with the archive will prevent this.

**Comment by AYu1804** [comment]
Idea: utilise kingpin$summary_data more? If archive gets really long as well - make sure summary_data is fully populated by the contents of the archive (but summarised). This is based on the idea that we dont need the full details from the record-level data. 

Work on making summary-data more detailed in the above case

**Comment by wyuill** [comment]
Perhaps rather than 100 rows (as this may drop instances of a given pin) this could keep the last x of each pin (at least until the pin is deleted)

**Comment by AYu1804** [comment]
I've made a job script here that can be scheduled as an independent job to periodically clear kingpin$records and transfer to a kingpin_summary dataset https://github.com/herts-phei/kingpin/blob/master/inst/clean_kingpin.R
